version: '3.8'

services:
  portal:
    build:
      context: ./portal  # Path to the Portal directory
    container_name: portal_container
    ports:
      - "5000:5000"  # Expose the Portal on localhost:5000
    networks:
      - brogue_network

  brogue-game:
    build:
      context: ./brogue-game  # Path to the Brogue game directory
    container_name: brogue_game_container
    depends_on:
      - portal  # Ensures Portal starts before metrics-sender
    environment:
      - PORTAL_URL=http://portal_container:5000/metrics  # Use internal Docker hostname for Portal
    ports:
      - "15900:15900"
      - "16080:16080"
      - "18000:18000"
    networks:
      - brogue_network

networks:
  brogue_network:
    driver: bridge
