apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: monsters
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    http {
      server {
        listen 80;
        server_name localhost;

        # Serve images from /usr/share/nginx/html/images
        location /images/ {
          alias /usr/share/nginx/html/images/;
          try_files $uri =404;
        }

        # Serve the main page and other content from /usr/share/nginx/html
        location / {
          root /usr/share/nginx/html;
          index 404.html;  # Use your 404 page as the default index page
        }

        # Define the 404 page
        error_page 404 /404.html;
        location = /404.html {
          root /usr/share/nginx/html;
          internal;  # Ensures the 404 page is not accessible directly
        }
      }
    }
