apiVersion: v1
kind: Service
metadata:
  name: brogue-service
  namespace: monsties
spec:
  selector:
    app: brogue
  type: ClusterIP  # Change to NodePort or LoadBalancer if external access is required
  ports:
  - name: novnc
    port: 6080
    targetPort: 6080
  - name: vnc
    port: 5900
    targetPort: 5900
