apiVersion: v1
kind: Service
metadata:
  name: monsters-nginx-goblin-80
  namespace: monsters
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-goblin
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}