apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dungeon-master-update-pods
  namespace: monsties
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dungeon-master-update-pods-binding
  namespace: monsties
subjects:
- kind: ServiceAccount
  name: dungeon-master-controller-manager
  namespace: dungeon-master-system
roleRef:
  kind: Role
  name: dungeon-master-update-pods
  apiGroup: rbac.authorization.k8s.io
