apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: monsters.kaschaefer.com
  labels:
    app: dungeon-master
  annotations:
    description: "CRD for managing Monster resources in the K8s Brogue game."
spec:
  group: kaschaefer.com
  names:
    kind: Monster
    listKind: MonsterList
    plural: monsters
    singular: monster
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  description: "The name of the monster."
                  nullable: true
                type:
                  type: string
                  description: "The type of monster (e.g., Goblin, Dragon)."
                  enum: ["Goblin", "Dragon", "Orc", "Bloat"]
                id:
                  type: integer
                  description: "The unique ID of the monster."
                health:
                  type: integer
                  description: "The current health points of the monster."
                  minimum: 0
                  maximum: 1000
                  nullable: true
          required:
            - spec
      subresources:
        status: {}
