apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dungeon-master-controller-manager-configmap
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "services", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["", "apps"]
    resources: ["services"]  # Add services resource
    verbs: ["list", "watch"]  # Allow listing and watching services