# permissions for end users to view monsters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dungeon-master
    app.kubernetes.io/managed-by: kustomize
  name: monster-viewer-role
rules:
- apiGroups:
  - kaschaefer.com
  resources:
  - monsters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kaschaefer.com
  resources:
  - monsters/status
  verbs:
  - get
