apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: portal-role-monsties
  namespace: monsties
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
