apiVersion: v1
kind: Service
metadata:
  name: portal-service
  namespace: portal
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: portal
  type: ClusterIP
  ports:
    - name: metrics
      port: 5000
      targetPort: 5000

