apiVersion: v1
kind: Service
metadata:
  name: portal-service
  namespace: portal
spec:
  selector:
    app: portal
  type: ClusterIP
  ports:
    - name: metrics
      port: 5000
      targetPort: 5000