apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: portal-clusterrole
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["kaschaefer.com"]
    resources: ["monsters"]
    verbs: ["get", "list", "watch", "create", "update", "delete"] 
