apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: dungeon-master
  labels:
    grafana_datasource: "1"
data:
  prometheus-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: dungeon-crawl-prom-ds
        type: prometheus
        access: proxy
        url: http://prometheus-service.dungeon-master.svc.cluster.local:9090
        isDefault: true
        jsonData:
          timeInterval: "1s"