apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dungeon-master-controller-manager-configmap-binding
subjects:
  - kind: ServiceAccount
    name: dungeon-master-controller-manager
    namespace: dungeon-master-system
roleRef:
  kind: ClusterRole
  name: dungeon-master-controller-manager-configmap
  apiGroup: rbac.authorization.k8s.io
