---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kaschaefer.com
  resources:
  - monsters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kaschaefer.com
  resources:
  - monsters/finalizers
  verbs:
  - update
- apiGroups:
  - kaschaefer.com
  resources:
  - monsters/status
  verbs:
  - get
  - patch
  - update
