from .index import bp  # Import 'bp' from index.py
from .monsters import bp  # Import 'bp' from monsters.py
from .metrics import bp  # Import 'bp' from metrics.py
from .player import bp  # Import 'bp' from player.py
from .gamestate import bp  # Import 'bp' from gamestate.py
from .gamestats import bp  # Import 'bp' from gamestats.py
from .items import bp  # Import 'bp' from items.py
from .pack import bp  # Import 'bp' from pack.py
from .game import bp  # Import 'bp' from game.py