{
 "title": "K8s Dungeon Crawl Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "K8s Dungeon Crawl",
   "type": "text",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<iframe src=\"http://localhost:8090/vnc.html\" style=\"width:100%; height:100%; border:none;\"></iframe>"
   }
  },
  {
   "title": "Gold",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "brogue_player_gold" }
   ]
  },
  {
   "title": "Current HP",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "brogue_player_current_hp" }
   ]
  },
  {
   "title": "Dungeon Level",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "brogue_depth_level" }
   ]
  },
  {
   "title": "Monster Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "brogue_monster_count_created", "legendFormat": "__auto" }
   ]
  }
 ]
}